apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-scraper-cron
spec:
  schedule: "0 * * * *" # Run hourly
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web-scraper
            image: gcr.io/vidwanscientistsdata/web-scraper:latest
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/vidwanscientistsdata-9f8473344db5.json
            volumeMounts:
            - name: gcs-credentials
              mountPath: /app/vidwanscientistsdata-9f8473344db5.json
              subPath: credentials.json
          volumes:
          - name: gcs-credentials
            secret:
              secretName: gcs-credentials-secret
          restartPolicy: OnFailure
