apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-scraper-cron
spec:
  schedule: "0 * * * *" # Run hourly
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "614415855935-compute@developer.gserviceaccount.com"  # Kubernetes Service Account linked to GSA
          containers:
          - name: web-scraper
            image: gcr.io/vidwanscientistsdata/data-scraper:latest  
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /vidwanscientistsdata-9f8473344db5.json  
            volumeMounts:
            - name: gcp-key
              mountPath: / 
              readOnly: true
          volumes:
          - name: gcp-key
            secret:
              secretName: gcp-key-secret
          restartPolicy: OnFailure
