apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-scraper-cron
spec:
  schedule: "0 * * * *" # Run hourly
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web-scraper
            image: gcr.io/vidwanscientistsdata/web-scraper:latest


